### ISSUE TITLE
在1.2.10上不能用

### ISSUE THREAD

**Issue by Dmitri233** [MamoeTech/Nukkit-WorldProtect#1]
在这里用中文发会不会很尴尬
 09.02 16:30:54 [服务器] 信息 DK
09.02 16:30:54 [服务器] 信息 GK16:30:54 [INFO] [控制台: 已保存世界]
09.02 16:30:54 [服务器] 信息 DK
09.02 16:30:54 [服务器] 信息 GK16:30:54 [INFO] [控制台: 保存中...]
09.02 16:30:54 [服务器] 信息 DK
09.02 16:30:54 [服务器] 信息 GK16:30:54 [INFO] [控制台: 世界自动保存已开启]
09.02 16:30:54 [服务器] 信息 save-all
09.02 16:30:54 [服务器] 信息 save-on
09.02 16:30:54 [面板] 保存地图...
09.02 16:30:00 [服务器] 信息 DK
09.02 16:30:00 [服务器] 信息 GK16:30:00 [INFO] Memory freed: 410.45 MB
09.02 16:30:00 [服务器] 信息 DK
09.02 16:30:00 [服务器] 信息 GK16:30:00 [INFO] Block Entities: 144
09.02 16:30:00 [服务器] 信息 DK
09.02 16:30:00 [服务器] 信息 GK16:30:00 [INFO] Entities: 1
09.02 16:30:00 [服务器] 信息 DK
09.02 16:30:00 [服务器] 信息 GK16:30:00 [INFO] Chunks: 710
09.02 16:30:00 [服务器] 信息 DK
09.02 16:30:00 [服务器] 信息 GK16:30:00 [INFO] ---- Garbage collection result ----
09.02 16:30:00 [服务器] 信息 gc
09.02 16:30:00 [服务器] 信息 DK
09.02 16:30:00 [面板] Server ran 命令 清理gc
09.02 16:29:55 [服务器] 信息 GK16:29:55 [INFO] WildingSloth21[/223.104.91.85:36068] 登出游戏，原因： client disconnect
09.02 16:29:55 [服务器] 信息 DK
09.02 16:29:55 [服务器] 信息 GK16:29:55 [INFO] 玩家 WildingSloth21 离开服务器
09.02 16:29:50 [服务器] 信息 DK
09.02 16:29:50 [服务器] 信息 ... 22 more
09.02 16:29:50 [服务器] 信息 at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
09.02 16:29:50 [服务器] 信息 at java.lang.reflect.Method.invoke(Method.java:498)
09.02 16:29:50 [服务器] 信息 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09.02 16:29:50 [服务器] 信息 at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
09.02 16:29:50 [服务器] 信息 at world.protect.Listener.EventListener.onPlayerTeleportEvent(EventListener.java:49)
09.02 16:29:50 [服务器] 信息 at world.protect.Listener.EventListener.setIf(EventListener.java:66)
09.02 16:29:50 [服务器] 信息 at world.protect.Listener.EventListener.setGamemode(EventListener.java:60)
09.02 16:29:50 [服务器] 信息 Caused by: java.lang.NoSuchMethodError: cn.nukkit.AdventureSettings.setCanFly(Z)V
09.02 16:29:50 [服务器] 信息 at cn.nukkit.Nukkit.main(Nukkit.java:102)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.Server.<init>(Server.java:498)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.Server.start(Server.java:815)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.Server.tickProcessor(Server.java:838)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.Server.tick(Server.java:1064)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.network.Network.processInterfaces(Network.java:76)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.raknet.server.ServerH和ler.h和lePacket(ServerH和ler.java:132)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.network.RakNetInterface.h和leEncapsulated(RakNetInterface.java:157)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.Player.h和leDataPacket(Player.java:2049)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.network.Network.processBatch(Network.java:160)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.network.Network.processPackets(Network.java:178)
09.02 16:29:50 [服务器] 信息 at java.util.ArrayList.forEach(ArrayList.java:1249)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.Player.h和leDataPacket(Player.java:2622)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.Server.dispatch命令(Server.java:678)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.命令.Simple命令Map.dispatch(SimpleComm和Map.java:247)
09.02 16:29:50 [服务器] 信息 at net.mcpes.summit.hhm.multiworld.命令.Transfer命令.execute(TransferComm和.java:34)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.entity.Entity.teleport(Entity.java:1862)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.entity.Entity.teleport(Entity.java:1866)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.Player.teleport(Player.java:4037)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
09.02 16:29:50 [服务器] 信息 at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
09.02 16:29:50 [服务器] 信息 GK16:29:50 [ALERT] cn.nukkit.utils.EventException
09.02 16:29:50 [服务器] 信息 DK
09.02 16:29:50 [服务器] 信息 GK16:29:50 [CRITICAL] "无法处理事件 'cn.nukkit.event.player.PlayerTeleportEvent' 至 'WorldProtect v1.0.0'：null 在 world.protect.Listener.EventListener 上"

**Comment by WetABQ** [comment]
弃坑了（滑稽）

**Comment by WetABQ** [comment]
已经修复完毕
